version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      DB_USER: root
      DB_PASSWORD: toor
      DB_DATABASE: dev
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    external: true
