tags:
- name: API
  description: description API

paths:
# [GET]
  /:
    get:
      tags:
      - main
      summary: Main page
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
