/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AuthForgotPasswordBodyParams {
  email: string;
}

export interface ConfirmationQueryParams {
  action: 'confirm_email' | 'reset_password';
  email: string;
  token: string;
}

export interface LoginBodyParams {
  email: string;
  password: string;
  remember?: boolean;
}

export interface RegisterBodyParams {
  confirmPassword: any;
  email: string;
  password: string;
}
