/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LoginBodyData {
  email: string;
  password: string;
  remember?: boolean;
}
